import { defineConfig } from 'tsup'

export default defineConfig({
	entry: ['src/index.ts'],
	format: ['esm'],
	dts: { resolve: true },
	sourcemap: false,
	clean: true,
	splitting: false,
	minify: 'terser',
	terserOptions: {
		compress: {
			passes: 3,
			toplevel: true,
			unsafe: true,
			unsafe_comps: true,
			unsafe_math: true,
			unsafe_methods: true,
			unsafe_regexp: true,
			unsafe_undefined: true,
			collapse_vars: true,
			reduce_vars: true,
			drop_console: false,
			drop_debugger: true,
			booleans_as_integers: true,
			pure_getters: true,
			negate_iife: true,
			hoist_funs: true,
			hoist_vars: false,
			if_return: true,
			join_vars: true,
			sequences: true,
			switches: true,
			dead_code: true,
			conditionals: true,
			evaluate: true,
			unused: true,
		},
		mangle: {
			toplevel: true,
			properties: false,
		},
		format: {
			comments: false,
			ascii_only: true,
			wrap_iife: true,
		},
	},
	target: 'es2015',
	outDir: 'dist',
})
